### ISSUE TITLE
Feature: User can receive a quote

### ISSUE THREAD

**Issue by solomonjin** [mosesr-kim/type-fighter#11]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can receive a quote from an API

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Create a separate module in the server directory
- [x] This module will retrieve a random quote from the quotable API 
- [x] Format the received quote then return it
- [x] Test through console
- [x] Handle all errors and respond to the client

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
